---
title: "k-means στην R"
author: "Leonidas Liakos"
date: "5/27/2022"
output: html_document
source: "https://uc-r.github.io/kmeans_clustering"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Το τρέχον notebook αποτελεί έναν οδηγό για την εκτέλεση συσταδοποίησης δεδομένων με τον διαμεριστικό αλγόριθμο k-means


# Εισαγωγή των απαραίτητων βιβλιοθηκών

Αρχικά εισάγουμε τις απαραίτητες βιβλιοθήκες για την διεκπεραίωση της διαδικασίας. 
Σε περίπτωση που δεν είναι εγκατεστημένες πρέπει να εγκατασταθούν.

```{r message=FALSE, warning=FALSE}
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
```
```{r}
# data <- read_csv("data/Country-data.csv") %>% remove_rownames %>% column_to_rownames(var="country") 
data <- USArrests

```

```{r}
data <- na.omit(data)
data <- scale(data)

```



```{r}
#Elbow Method for finding the optimal number of clusters
set.seed(123)
# Compute and plot wss for k = 2 to k = 15.
k.max <- 15
wss <- sapply(1:k.max, 
              function(k){kmeans(data, k, nstart=50,iter.max = 15 )$tot.withinss}) # tot.withinss: Total within-cluster sum of squares, i.e. sum(withinss).
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
```

```{r}
distance <- get_dist(data)
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```
```{r}
k2 <- kmeans(data, centers = 3, nstart = 25)
str(k2)
```

```{r}
k2
```
```{r}
fviz_cluster(k2, data = data)
```

